{{- if and (not .Values.coturn.staticSecret.secretName) .Values.coturn.staticSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coturn.fullname" . }}-static-secret
type: Opaque
data:
  {{ .Values.coturn.staticSecret.secretKey | quote }}: {{ .Values.coturn.staticSecret.value | b64enc | quote }}
{{- end }}