{{- if .Values.vaultwarden.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vaultwarden.fullname" . }}
  labels:
    {{- include "vaultwarden.selectorLabels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.vaultwarden.createSecret }}
{{- if $value }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}