{{- if .Values.tls.request.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "znc.fullname" . }}
spec:
  dnsNames:
  {{- .Values.tls.request.dnsNames | required "dnsNames are required!" | toYaml | nindent 4 }}
  issuerRef:
    group: cert-manager.io
    kind: {{ .Values.tls.request.issuerRef.kind }}
    name: {{ .Values.tls.request.issuerRef.name | required "the issuer name is required!" }}
  secretName: {{ .Values.tls.request.secretName | required "the secret name is required!" }}
  usages:
  - digital signature
  - key encipherment
{{- end }}
