{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "znc.fullname" . }}
  labels:
    {{- include "znc.labels" . | nindent 4 }}
spec:
    {{- .Values.persistence.pvc | required "the pvc spec is required!" | toYaml | nindent 4 }}
{{- end }}
