{{- if not .Values.graylog.existingRootSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "graylog.fullname" . }}
  labels:
{{ include "graylog.metadataLabels" . | indent 4 }}
{{- if .Values.graylog.secret.annotations }}
  annotations:
    {{- toYaml .Values.graylog.secret.annotations | nindent 4 }}
{{- end }}
type: Opaque
data:
  graylog-root-username: {{ .Values.graylog.rootUsername | b64enc | quote }}
  {{- if not .Values.graylog.rootPassword }}
  {{- fail "No root password and no existing secret was provided!" }}
  {{- end }}
  graylog-password-secret: {{ .Values.graylog.rootPassword | b64enc | quote }}
  graylog-password-sha2: {{ .Values.graylog.rootPassword | sha256sum | b64enc | quote }}
{{- end }}
