apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ print .Values.s3Backup.roleName "-binding" | quote }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.s3Backup.serviceAccountName | quote }}
roleRef:
  kind: Role
  name: {{ $.Values.s3Backup.roleName | quote }}
  apiGroup: rbac.authorization.k8s.io
