{{- if not .Values.s3Backup.secrets.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print .Values.s3Backup.jobName "-secrets" | quote }}
data:
    RESTIC_PASSWORD: {{ .Values.s3Backup.secrets.resticPassword | b64enc | quote }}
    {{- range $name, $value := (.Values.s3Backup.secrets.resticEnvVars | default dict) }}
    {{ $name }}: {{ $value | b64enc | quote }}
    {{- end }}
{{- end }}