{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- $hosts := list (index (regexSplit "/" .Values.hostname -1) 2) }}
  {{- with .Values.adminHostname }}
  {{- $hosts = append $hosts (index (regexSplit "/" .  -1) 2) }}
  {{- end }}
  {{- $hosts = concat $hosts .Values.ingress.extraHosts }}
  rules:
    {{- range $host := $hosts }}
    - host: {{ $host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "keycloak.fullname" $ }}-service
                port:
                  name: http 
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls: {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}