{{- if not .Values.secretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cert-manager-webhook-cloudns.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "cert-manager-webhook-cloudns.name" . }}
data:
  auth_id: {{ .Values.clouDNS.auth_id | b64enc | quote }}
  auth_password: {{ .Values.clouDNS.auth_password | b64enc | quote }}
{{- end }}
