apiVersion: v1
appVersion: "1.1.0"
description: A helm chart for cert-manager-webhook-cloudns
name: cert-manager-webhook-cloudns
# renovate: image=ghcr.io/pschichtel/cert-manager-webhook-cloudns
version: 1.2.0
