replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  # imagePullPolicy is not supported: https://github.com/keycloak/keycloak/issues/34829
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

keycloak-operator:
  enabled: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

tolerations: []

affinity: {}

db: null
hostname: null
startOptimized: null
features:
  enabled:
  - docker
  - authorization

ingress:
  enabled: false
  extraHosts: []
  tls: []

additionalOptions: {}

serviceMonitor:
  enabled: false
  path: /auth/metrics
  additionalEndpoints: []
