apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustdesk-server-oss.fullname" . }}
  labels:
    {{- include "rustdesk-server-oss.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
    - name: "relay-port"
      targetPort: {{ .Values.service.hbbr.replayPort.targetPort }}
      port: {{ .Values.service.hbbr.replayPort.port }}
      protocol: TCP
    {{ if .Values.service.enableWebClientSupport }}
    - name: "client-port"
      targetPort: {{.Values.service.hbbr.clientPort.targetPort }}
      port: {{ .Values.service.hbbr.clientPort.port }}
      protocol: TCP
    {{ end }}
    - name: "nat-port"
      port: {{ .Values.service.hbbs.natPort.port }}
      protocol: TCP
      targetPort: 21115
    - name: "registry-port"
      port: {{ .Values.service.hbbs.registryPort.port }}
      targetPort: 21116
      protocol: TCP
    - name: "heartbeat-port"
      port: {{ .Values.service.hbbs.heartbeatPort.port }}
      protocol: UDP
      targetPort: 21116
    {{ if .Values.service.enableWebClientSupport }}
    - port: {{ .Values.service.hbbs.webPort.port }}
      targetPort: 21118
      protocol: TCP
      name: "web-port"
    {{end}}
  selector:
    {{- include "rustdesk-server-oss.selectorLabels" . | nindent 4 }}
