apiVersion: v1
kind: Service
metadata:
  name: {{ include "rustdesk-server-oss.fullname" . }}
  labels:
    {{- include "rustdesk-server-oss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  ports:
    - name: "hbbr-relay-port"
      targetPort: {{ .Values.service.hbbr.replayPort.targetPort }}
      port: {{ .Values.service.hbbr.replayPort.port }}
      protocol: TCP
    {{ if .Values.service.hbbr.clientPort.enable }}
    - name: "hbbr-client-port"
      targetPort: {{.Values.service.hbbr.clientPort.targetPort }}
      port: {{ .Values.service.hbbr.clientPort.port }}
      protocol: TCP
    {{ end }}
    - name: "hbbs-nat-port"
      port: {{ .Values.service.hbbs.natPort.port }}
      protocol: TCP
      targetPort: 21115
    - name: "hbbs-registry-port"
      port: {{ .Values.service.hbbs.registryPort.port }}
      targetPort: 21116
      protocol: TCP
    - name: "hbbs-heartbeat-port"
      port: {{ .Values.service.hbbs.heartbeatPort.port }}
      protocol: UDP
      targetPort: 21116
    {{ if .Values.service.hbbs.webPort.enable }}
    - port: {{ .Values.service.hbbs.webPort.port }}
      targetPort: 21118
      protocol: TCP
      name: "hbbs-web-port"
    {{end}}
  selector:
    {{- include "rustdesk-server-oss.selectorLabels" . | nindent 4 }}
