apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
    {{- include "teamspeak.selectorLabels" . | nindent 4 }}
data:
  {{- if .Values.configs.allowlist }}
  allowlist.txt: |
    {{- range .Values.configs.allowlist }}
    {{ . }}
    {{- end }}
  {{- end }}
