{{- range $serviceMonitorName, $serviceMonitor := .Values.serviceMonitors }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ print $.Release.Name "-external-" $serviceMonitorName | quote }}
  labels:
    {{- include "external-service-monitor.labels" $ | nindent 4 }}
    schich.tel/external-service-monitor: {{ $serviceMonitorName | quote }}
    {{- with $serviceMonitor.jobLabel }}
    {{ .name | quote }}: {{ .value | quote }}
    {{- end }}
spec:
  ports:
  {{- range $exporterName, $exporter := $serviceMonitor.exporters }}
  - protocol: TCP
    name: {{ $exporterName | quote }}
    port: {{ $exporter.port }}
    targetPort: {{ $exporter.port }}
  {{- end }}
{{- end }}