{{- range $serviceMonitorName, $serviceMonitor := .Values.serviceMonitors }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ print $.Release.Name "-external-" $serviceMonitorName | quote }}
  labels:
    {{- include "external-service-monitor.labels" $ | nindent 4 }}
    schich.tel/external-service-monitor: {{ $serviceMonitorName | quote }}
spec:
  endpoints:
  {{- range $exporterName, $exporter := $serviceMonitor.exporters }}
  - interval: {{ $exporter.interval | default $.Values.defaults.interval | required "each exporter needs an interval!" | quote }}
    targetPort: {{ $exporterName | quote }}
    path: {{ $exporter.endpoint | default $.Values.defaults.endpoint | required "each exporter needs an endpoint!" | quote }}
  {{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "external-service-monitor.selectorLabels" $ | nindent 6 }}
      schich.tel/external-service-monitor: {{ $serviceMonitorName | quote }}
{{- end }}