apiVersion: v2
name: powerdns
description: A Helm chart to deploy PowerDNS to Kubernetes
home: https://www.powerdns.com/
type: application
version: 0.8.0
# renovate: image=docker.io/powerdns/pdns-auth-48
appVersion: "4.8.4"
