apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "restic-forget.fullname" . }}
  labels:
    {{- include "restic-forget.labels" . | nindent 4 }}
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
