apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "restic-forget.fullname" . }}
  labels:
    {{- include "restic-forget.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "restic-forget.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "restic-forget.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
