apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ print .Values.roleName "-binding" | quote }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccountName | quote }}
roleRef:
  kind: Role
  name: {{ .Values.roleName | quote }}
  apiGroup: rbac.authorization.k8s.io
