{{- range $repo := .Values.repos }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print "restic-forget-" $repo.name "-secrets" | quote }}
data:
    RESTIC_REPOSITORY: {{ $repo.repo | b64enc | quote }}
    RESTIC_PASSWORD: {{ $repo.password | b64enc | quote }}
    {{- range $name, $value := $repo.extraEnv }}
    {{ $name }}: {{ $value | b64enc | quote }}
    {{- end }}
{{- end }}