{{- range $repo := .Values.repos }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print (include "restic-forget.fullname" $) "-" $repo.name | quote }}
  labels:
    {{- include "restic-forget.labels" $ | nindent 4 }}
data:
    RESTIC_REPOSITORY: {{ $repo.repo | b64enc | quote }}
    RESTIC_PASSWORD: {{ $repo.password | b64enc | quote }}
    {{- range $name, $value := $repo.extraEnv }}
    {{ $name }}: {{ $value | b64enc | quote }}
    {{- end }}
{{- end }}