{{- if and .Values.persistence.enabled (not .Values.persistence.existingPvc) -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "sponge-vanilla.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}