apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextcloud-notify_push.fullname" . }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.notify_push.databaseUrl | required "databaseUrl is required!" | b64enc }}
  REDIS_URL: {{ .Values.notify_push.redisUrl | required "redisUrl is required!" | b64enc }}