imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  # this is aligned with the cubeengine/sponge container image
  fsGroup: 1000

service:
  type: ClusterIP
  loadBalancerIP: null
  extraPorts: []

nodeSelector: {}

tolerations: []

affinity: {}

minecraft:
  image:
    repository: ghcr.io/cubeengine/sponge
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  ports:
    minecraft:
      port: 25565
    query:
      port: 25565
      expose: false
    rcon:
      port: 25575
      expose: false

  env:
    EULA: 'false'

  # healthcheck:
  #   tcpSocket:
  #     port: mc

  extraPorts: []
  extraVolumeMounts: []

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


extraVolumes: []

extraContainers: []

persistence:
  enabled: false
  existingClaim: null
  storageClassName: ''
  size: 5Gi
