apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pdns.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pdns.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ print .Values.image.repository ":" (.Values.image.tag | default (print "v" .Chart.AppVersion)) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/entrypoint.sh"]
          args:
          - "--webserver=yes"
          - "--webserver-port={{ .Values.powerdns.webserver.bindPort }}"
          - "--webserver-address=0.0.0.0"
          - "--webserver-allow-from={{ .Values.powerdns.webserver.allowFrom }}"
          - "--slave=yes"
          - "--dnsupdate={{ .Values.powerdns.dnsupdate.enabled }}"
          env:
          - name: PDNS_AUTH_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "pdns.fullname" . }}
                key: PDNS_AUTH_API_KEY
                optional: false
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: api
              containerPort: {{ .Values.powerdns.webserver.bindPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
