apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "pdns.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "pdns.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ print .Values.image.repository ":" (.Values.image.tag | default .Chart.AppVersion) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: api
              containerPort: {{ .Values.powerdns.webserver.bindPort }}
              protocol: TCP
          {{- if .Values.powerdns.webserver.password.key }}
          livenessProbe:
            tcpSocket:
              port: api
          readinessProbe:
            tcpSocket:
              port: api
          {{- else }}
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          {{- end }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
          env:
          - name: TEMPLATE_FILES
            value: '0-api.conf,1-webserver.conf,2-database.conf,3-dnsupdate.conf,4-additional.conf'
          {{ include "pdns.secretRef" (dict "Root" $ "Name" "PDNS_API_KEY" "Ref" .Values.powerdns.api.key) | nindent 10 }}
          {{ include "pdns.secretRef" (dict "Root" $ "Name" "PDNS_WEBSERVER_PASSWORD" "Ref" .Values.powerdns.webserver.password) | nindent 10 }}
          {{ include "pdns.secretRef" (dict "Root" $ "Name" "PDNS_DB_USERNAME" "Ref" .Values.powerdns.db.username) | nindent 10 }}
          {{ include "pdns.secretRef" (dict "Root" $ "Name" "PDNS_DB_PASSWORD" "Ref" .Values.powerdns.db.password) | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ template "pdns.fullname" . }}
              optional: true
          volumeMounts:
          - name: config
            subPath: pdns.conf
            mountPath: /etc/powerdns/pdns.conf
            readOnly: true
          - name: config
            mountPath: /etc/powerdns/templates.d
            readOnly: true
      volumes:
      - name: config
        configMap:
          name: {{ template "pdns.fullname" . }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
