apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pdns.fullname" . }}
type: Opaque
data:
  {{- with .Values.powerdns.api.key.value }}
  PDNS_API_KEY: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.powerdns.webserver.password.value }}
  PDNS_WEBSERVER_PASSWORD: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.powerdns.db.username.value }}
  PDNS_DB_USERNAME: {{ . | b64enc }}
  {{- end }}
  {{- with .Values.powerdns.db.password.value }}
  PDNS_DB_PASSWORD: {{ . | b64enc }}
  {{- end }}
