apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  database.conf: {{ template .Values.powerdns.db.configTemplate $ | b64enc }}
  PDNS_AUTH_API_KEY: {{ .Values.powerdns.api.key | b64enc }}
