{{- if .Values.powerdns.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
type: Opaque
data:
{{- range $name, $value := .Values.powerdns.createSecret }}
  {{ $name }}: {{ $value | b64enc }}
{{- end }}
{{- end }}