apiVersion: v1
kind: Secret
metadata:
  name: {{ template "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
type: Opaque
data:
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_API_KEY" "Ref" .Values.powerdns.api.key) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_WEBSERVER_PASSWORD" "Ref" .Values.powerdns.webserver.password) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_DB_HOST" "Ref" .Values.powerdns.db.host) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_DB_PORT" "Ref" .Values.powerdns.db.port) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_DB_NAME" "Ref" .Values.powerdns.db.name) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_DB_USERNAME" "Ref" .Values.powerdns.db.username) | nindent 2 -}}
{{- include "powerdns.secret" (dict "Root" $ "Name" "PDNS_DB_PASSWORD" "Ref" .Values.powerdns.db.password) | nindent 2 -}}