apiVersion: v1
kind: Service
metadata:
  name: {{ include "powerdns.fullname" . }}
  labels:
    {{- include "powerdns.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.powerdns.webserver.bindPort }}
      targetPort: {{ .Values.powerdns.webserver.bindPort }}
      protocol: TCP
      name: webserver
    - port: 53
      targetPort: 5353
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 5353
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "powerdns.selectorLabels" . | nindent 4 }}
