apiVersion: v1
kind: Service
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app: {{ template "pdns.name" . }}
    release: {{ .Release.Name }}
  ports:
    - port: {{ .Values.powerdns.webserver.bindPort }}
      targetPort: {{ .Values.powerdns.webserver.bindPort }}
      protocol: TCP
      name: api
    - port: 53
      targetPort: 53
      protocol: TCP
      name: dns-tcp
    - port: 53
      targetPort: 53
      protocol: UDP
      name: dns-udp
