apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "powerdns-admin.fullname" . }}
  labels:
    {{- include "powerdns-admin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "powerdns-admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "powerdns-admin.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
          - name: SECRET_KEY
            {{- if .Values.powerdnsAdmin.config.secretKeySecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.powerdnsAdmin.config.secretKeySecret.secret | quote }}
                key: {{ .Values.powerdnsAdmin.config.secretKeySecret.key | quote }}
            {{- else }}
            value: {{ .Values.powerdnsAdmin.config.secretKey | required ".Values.powerdnsAdmin.config.secretKey or .Values.powerdnsAdmin.config.secretKeySecret is required!" | quote }}
            {{- end }}
          - name: SQLALCHEMY_DATABASE_URI
            {{- if .Values.powerdnsAdmin.config.databaseUriSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.powerdnsAdmin.config.databaseUriSecret.secret | quote }}
                key: {{ .Values.powerdnsAdmin.config.databaseUriSecret.key | quote }}
            {{- else }}
            value: {{ .Values.powerdnsAdmin.config.databaseUri | required ".Values.powerdnsAdmin.config.databaseUri or .Values.powerdnsAdmin.config.databaseUriSecret is required!" | quote }}
            {{- end }}
          - name: LOG_LEVEL
            value: {{ .Values.powerdnsAdmin.config.logLevel | default "DEBUG" | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
