replicaCount: 1

image:
  repository: ghcr.io/dani-garcia/vaultwarden
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP

ingress:
  enabled: false
  className: ""
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  enabled: false
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi

vaultwarden:
  logLevel: info
  createSecret: null
  commonSecret: null
  settings:
    signupsAllowed: false
    # only if `signupsAllowed` is true
    signupsDomainsWhitelist: []
    invitationsAllowed: false
    adminToken:
      key: ADMIN_TOKEN
    pushEnabled: false
    pushInstallationId:
      key: PUSH_INSTALLATION_ID
    pushInstallationKey:
      key: PUSH_INSTALLATION_KEY
    domain: null
    yubicoServer: null
    # this must be a secretKeyRef with optional secret name
    yubicoClientId: null
    # this must be a secretKeyRef with optional secret name
    yubicoSecretKey: null
    rocketLimits: null
    rocketWorkers: null
    smtpHost: null
    smtpFrom: null
    smtpPort: null
    smtpSecurity: null
    # this must be a secretKeyRef with optional secret name
    smtpUsername: null
    # this must be a secretKeyRef with optional secret name
    smtpPassword: null
    showPasswordHint: false
    webVaultEnabled: true
    logLevel: null
    extendedLogging: null
  database:
    uri: postgresql://$(VAULTWARDEN_DB_USERNAME):$(VAULTWARDEN_DB_PASSWORD)@example.org:5432/vaultwarden
    username:
      key: VAULTWARDEN_DB_USERNAME
    password:
      key: VAULTWARDEN_DB_PASSWORD
