apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- /* for more robust HTTPS detection in fcgi applications */}}
    map $http_x_forwarded_proto $fastcgi_https {
        default '';
        https 'on';
    }

    server {
        listen       8080 default;
        server_name  _;
        charset      utf-8;
        
        root         /app;
        
        server_tokens off;

        include /default-server-early/*.conf;

{{- $keys := keys .Values.nginxConfig.serverSnippets | sortAlpha }}
{{- range $key := $keys }}
{{- $value := get $.Values.nginxConfig.serverSnippets $key }}
{{- if ne $value nil }}
        # Snippet: {{ $key }}
        {{- $value | nindent 8 }}
{{- end }}
{{- end }}

        include /default-server/*.conf;
    }

    include /nginx/*.conf;
  types.conf: |-
    types {
        text/html                             html htm shtml;
        text/css                              css;
        text/xml                              xml rss;
        image/gif                             gif;
        image/jpeg                            jpeg jpg;
        application/x-javascript              js;
        text/plain                            txt;
        text/x-component                      htc;
        text/mathml                           mml;
        image/png                             png;
        image/x-icon                          ico;
        image/x-jng                           jng;
        image/vnd.wap.wbmp                    wbmp;
        image/webp                            webp;
        image/avif                            avif;
        application/java-archive              jar war ear;
        application/mac-binhex40              hqx;
        application/pdf                       pdf;
        application/x-cocoa                   cco;
        application/x-java-archive-diff       jardiff;
        application/x-java-jnlp-file          jnlp;
        application/x-makeself                run;
        application/x-perl                    pl pm;
        application/x-pilot                   prc pdb;
        application/x-rar-compressed          rar;
        application/x-redhat-package-manager  rpm;
        application/x-sea                     sea;
        application/x-shockwave-flash         swf;
        application/x-stuffit                 sit;
        application/x-tcl                     tcl tk;
        application/x-x509-ca-cert            der pem crt;
        application/x-xpinstall               xpi;
        application/zip                       zip;
        application/octet-stream              deb;
        application/octet-stream              bin exe dll;
        application/octet-stream              dmg;
        application/octet-stream              eot;
        application/octet-stream              iso img;
        application/octet-stream              msi msp msm;
        audio/mpeg                            mp3;
        audio/x-realaudio                     ra;
        video/mpeg                            mpeg mpg;
        video/quicktime                       mov;
        video/x-flv                           flv;
        video/x-msvideo                       avi;
        video/x-ms-wmv                        wmv;
        video/x-ms-asf                        asx asf;
        video/x-mng                           mng;
    }
  fastcgi_params: |-
    fastcgi_param  QUERY_STRING       $query_string;
    fastcgi_param  REQUEST_METHOD     $request_method;
    fastcgi_param  CONTENT_TYPE       $content_type;
    fastcgi_param  CONTENT_LENGTH     $content_length;

    fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_param  REQUEST_URI        $request_uri;
    fastcgi_param  DOCUMENT_URI       $document_uri;
    fastcgi_param  DOCUMENT_ROOT      $document_root;
    fastcgi_param  SERVER_PROTOCOL    $server_protocol;
    fastcgi_param  REQUEST_SCHEME     $scheme;
    fastcgi_param  HTTPS              $fastcgi_https if_not_empty;

    fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
    fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

    fastcgi_param  REMOTE_ADDR        $remote_addr;
    fastcgi_param  REMOTE_PORT        $remote_port;
    fastcgi_param  SERVER_ADDR        $server_addr;
    fastcgi_param  SERVER_PORT        $server_port;
    fastcgi_param  SERVER_NAME        $server_name;

    # PHP only, required if PHP was built with --enable-force-cgi-redirect
    fastcgi_param  REDIRECT_STATUS    200;

  php.ini: |-
    ; Config as generated by helm
    {{- range $name, $value := .Values.php.ini }}
    {{ $name }} = {{ tpl $value $ }};
    {{- end }}
    {{- if .Values.php.opcache.enabled }}
    opcache.enable = 1;
    opcache.file_cache = /opcache
    {{- end }}
    {{- tpl .Values.php.rawIni $ | nindent 4 }}
  php-fpm.ini: |-
    ; Config as generated by helm
    {{- if or .Values.php.fpmGlobalIni .Values.php.rawFpmGlobalIni }}
    [global]
    {{- range $name, $value := .Values.php.fpmGlobalIni }}
    {{ $name }} = {{ tpl $value $ }}
    {{- end }}
    {{- tpl .Values.php.rawFpmGlobalIni $ | nindent 4 }}
    {{- end }}
    [www]
    {{- range $name, $value := .Values.php.fpmPoolIni }}
    {{ $name }} = {{ tpl $value $ }}
    {{- end }}
    {{- tpl .Values.php.rawFpmPoolIni $ | nindent 4 }}
    {{- if .Values.exporter.enabled }}
    pm.status_path = {{ .Values.exporter.statusPath }}
    {{- end }}

