apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: wordpress
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wordpressImage.repository }}:{{ .Values.wordpressImage.tag | default (print .Chart.AppVersion "-fpm") }}"
          imagePullPolicy: {{ .Values.wordpressImage.pullPolicy }}
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.path | quote }}
              port: http
              httpHeaders:
                {{ .Values.probes.headers | toYaml | nindent 16 }}
            timeoutSeconds: {{ .Values.probes.timeout }}
            periodSeconds: {{ .Values.probes.period }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.path | quote }}
              port: http
              httpHeaders:
                {{ .Values.probes.headers | toYaml | nindent 16 }}
            timeoutSeconds: {{ .Values.probes.timeout }}
            periodSeconds: {{ .Values.probes.period }}
          {{- else }}
          livenessProbe:
            tcpSocket:
              port: fpm
          readinessProbe:
            tcpSocket:
              port: fpm
          {{- end }}
          resources:
            {{- toYaml .Values.wordpressResources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/www/html
            - name: configmap
              subPath: 'php.ini'
              mountPath: /usr/local/etc/php/conf.d/99-custom.ini
            - name: configmap
              subPath: 'php-fpm.ini'
              mountPath: /usr/local/etc/php-fpm.d/z-www.conf
            {{- if .Values.php.opcache.enabled }}
            - name: opcache
              mountPath: /opcache
            {{- end }}
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.nginxResources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /app
            - name: configmap
              subPath: 'nginx.conf'
              mountPath: /etc/nginx/conf.d/default.conf
              readOnly: true
            - name: configmap
              subPath: 'fastcgi_params'
              mountPath: /etc/nginx/fastcgi_params
              readOnly: true
            - name: configmap
              subPath: 'types.conf'
              mountPath: /etc/nginx/conf.d/types.conf
        {{- if .Values.exporter.enabled }}
        - name: exporter
          securityContext:
            {{- toYaml .Values.exporter.securityContext | nindent 12 }}
          image: "{{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}"
          imagePullPolicy: {{ .Values.wordpressImage.pullPolicy }}
          ports:
            - name: exporter
              containerPort: 9253
              protocol: TCP
          env:
            - name: PHP_FPM_SCRAPE_URI
              value: {{ print "tcp://127.0.0.1:9000" .Values.exporter.statusPath | quote }}
          resources:
            {{- toYaml .Values.exporter.resources | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ print (include "wordpress.fullname" .) "-pvc" | quote }}
        - name: configmap
          configMap:
            defaultMode: 0644
            name: {{ include "wordpress.fullname" . }}
        {{- if .Values.php.opcache.enabled }}
        - name: opcache
          emptyDir:
            {{- with .Values.php.opcache.medium }}
            medium: {{ . | quote }}
            {{- end }}
            sizeLimit: {{ .Values.php.opcache.size | quote }}
        {{- end -}}
