apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          imagePullPolicy: {{ .Values.nginxImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.nginxResources | nindent 12 }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /app
            - name: configmap
              subPath: 'nginx.conf'
              mountPath: /etc/nginx/conf.d/default.conf
            - name: configmap
              subPath: 'fastcgi_params'
              mountPath: /etc/nginx/fastcgi_params
            - name: configmap
              subPath: 'types.conf'
              mountPath: /etc/nginx/conf.d/types.conf
        - name: wordpress
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.wordpressImage.repository }}:{{ .Values.wordpressImage.tag | default (print .Chart.AppVersion "-php8.2-fpm") }}"
          imagePullPolicy: {{ .Values.wordpressImage.pullPolicy }}
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: fpm
          readinessProbe:
            tcpSocket:
              port: fpm
          resources:
            {{- toYaml .Values.wordpressResources | nindent 12 }}
          volumeMounts:
            - name: wordpress-data
              mountPath: /var/www/html
            - name: configmap
              subPath: 'php.ini'
              mountPath: /usr/local/etc/php/conf.d/99-custom.ini
            - name: configmap
              subPath: 'php-fpm.ini'
              mountPath: /usr/local/etc/php-fpm.d/z-www.conf
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: wordpress-data
          persistentVolumeClaim:
            claimName: {{ print (include "wordpress.fullname" .) "-pvc" | quote }}
        - name: configmap
          configMap:
            defaultMode: 0644
            name: {{ include "wordpress.fullname" . }}
