apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ print (include "wordpress.fullname" .) "-pvc" | quote }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
    {{- toYaml .Values.persistence.pvc | nindent 4 }}
