apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mediawiki.fullname" . }}
  labels:
    {{- include "mediawiki.selectorLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.mediawiki.installMode }}
  {{- $settings := (required "localSettings is required!" .Values.mediawiki.localSettings.content )}}
  {{- if .Values.mediawiki.localSettings.template }}
  LocalSettings.php: {{ tpl $settings $ | b64enc | quote }}
  {{- else }}
  LocalSettings.php: {{ $settings | b64enc | quote }}
  {{- end }}
  {{- end }}