{{- if and .Values.exporter.enabled .Values.exporter.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mediawiki.fullname" . }}
  labels:
    {{- include "mediawiki.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    targetPort: exporter
    path: /metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
    {{- include "mediawiki.selectorLabels" . | nindent 6 }}
{{- end -}}