apiVersion: v2
name: powerdns-admin
description: A PowerDNS web interface with advanced features
home: https://github.com/PowerDNS-Admin/PowerDNS-Admin
type: application
version: 0.5.1
appVersion: 0.4.2
